In [2]:
import numpy as np
from collections import Counter
from sklearn import datasets
import statistics as st
import pandas as pd
import time
from math import *
from matplotlib import pyplot as plt
from matplotlib import style
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
#import dataset
df = pd.read_csv('fetal_health2.csv')
y=df.iloc[:,-1].values

In [4]:
Baseline_Value = (df["baseline_value"] - df["baseline_value"].min())/ (df["baseline_value"].max() - df["baseline_value"].min())
Accelerations = (df["accelerations"] - df["accelerations"].min()) / (df["accelerations"].max() - df["accelerations"].min())
Fetal_Movement = (df["fetal_movement"] - df["fetal_movement"].min()) / (df["fetal_movement"].max() - df["fetal_movement"].min())
Uterine_Contractions = (df["uterine_contractions"] - df["uterine_contractions"].min()) / (df["uterine_contractions"].max() - df["uterine_contractions"].min())
Light_Decelerations = (df["light_decelerations"] - df["light_decelerations"].min()) / (df["light_decelerations"].max() - df["light_decelerations"].min())
Severe_Decelerations = (df["severe_decelerations"] - df["severe_decelerations"].min()) / (df["severe_decelerations"].max() - df["severe_decelerations"].min())
Prolongued_Decelerations = (df["prolongued_decelerations"] - df["prolongued_decelerations"].min()) / (df["prolongued_decelerations"].max() - df["prolongued_decelerations"].min())
Abnormal_Shortterm_Variability = (df["abnormal_short_term_variability"] - df["abnormal_short_term_variability"].min()) / (df["abnormal_short_term_variability"].max() - df["abnormal_short_term_variability"].min())
Meanvalue_of_Shortterm_Variability = (df["mean_value_of_short_term_variability"] - df["mean_value_of_short_term_variability"].min()) / (df["mean_value_of_short_term_variability"].max() - df["mean_value_of_short_term_variability"].min())
Percentage_of_Timewith_Abnormal_Longterm_Variability = (df["percentage_of_time_with_abnormal_long_term_variability"] - df["percentage_of_time_with_abnormal_long_term_variability"].min()) / (df["percentage_of_time_with_abnormal_long_term_variability"].max() - df["percentage_of_time_with_abnormal_long_term_variability"].min())
Mean_Value_of_Longterm_Variability = (df["mean_value_of_long_term_variability"] - df["mean_value_of_long_term_variability"].min()) / (df["mean_value_of_long_term_variability"].max() - df["mean_value_of_long_term_variability"].min())
Histogram_Width = (df["histogram_width"] - df["histogram_width"].min()) / (df["histogram_width"].max() - df["histogram_width"].min())
Histogram_Min = (df["histogram_min"] - df["histogram_min"].min()) / (df["histogram_min"].max() - df["histogram_min"].min())
Histogram_Max = (df["histogram_max"] - df["histogram_max"].min()) / (df["histogram_max"].max() - df["histogram_max"].min())
Histogram_Number_of_Peaks = (df["histogram_number_of_peaks"] - df["histogram_number_of_peaks"].min()) / (df["histogram_number_of_peaks"].max() - df["histogram_number_of_peaks"].min())
Histogram_Number_of_Zeroes = (df["histogram_number_of_zeroes"] - df["histogram_number_of_zeroes"].min()) / (df["histogram_number_of_zeroes"].max() - df["histogram_number_of_zeroes"].min())
Histogram_Mode = (df["histogram_mode"] - df["histogram_mode"].min()) / (df["histogram_mode"].max() - df["histogram_mode"].min())
Histogram_Mean = (df["histogram_mean"] - df["histogram_mean"].min()) / (df["histogram_mean"].max() - df["histogram_mean"].min())
Histogram_Median = (df["histogram_median"] - df["histogram_median"].min()) / (df["histogram_median"].max() - df["histogram_median"].min())
Histogram_Variance = (df["histogram_variance"] - df["histogram_variance"].min()) / (df["histogram_variance"].max() - df["histogram_variance"].min())
Histogram_Tendency = (df["histogram_tendency"] - df["histogram_tendency"].min()) / (df["histogram_tendency"].max() - df["histogram_tendency"].min())

In [5]:
import numpy as np
MinMax = []
MinMax.append(Baseline_Value)
MinMax.append(Accelerations)
MinMax.append(Fetal_Movement)
MinMax.append(Uterine_Contractions)
MinMax.append(Light_Decelerations)
MinMax.append(Severe_Decelerations)
MinMax.append(Prolongued_Decelerations)
MinMax.append(Abnormal_Shortterm_Variability)
MinMax.append(Meanvalue_of_Shortterm_Variability)
MinMax.append(Percentage_of_Timewith_Abnormal_Longterm_Variability)
MinMax.append(Mean_Value_of_Longterm_Variability)
MinMax.append(Histogram_Width)
MinMax.append(Histogram_Min)
MinMax.append(Histogram_Max)
MinMax.append(Histogram_Number_of_Peaks)
MinMax.append(Histogram_Number_of_Zeroes)
MinMax.append(Histogram_Mode)
MinMax.append(Histogram_Mean)
MinMax.append(Histogram_Median)
MinMax.append(Histogram_Variance)
MinMax.append(Histogram_Tendency)

In [6]:
normalisasi = pd.DataFrame(MinMax)
normalisasi.to_numpy()
dataset = normalisasi.T
dataset

baseline_value  accelerations  fetal_movement  uterine_contractions  \
0           0.259259       0.000000        0.000000              0.000000   
1           0.481481       0.315789        0.000000              0.400000   
2           0.500000       0.157895        0.000000              0.533333   
3           0.518519       0.157895        0.000000              0.533333   
4           0.481481       0.368421        0.000000              0.533333   
...              ...            ...             ...                   ...   
2121        0.629630       0.000000        0.000000              0.466667   
2122        0.629630       0.052632        0.000000              0.466667   
2123        0.629630       0.052632        0.000000              0.466667   
2124        0.629630       0.052632        0.000000              0.400000   
2125        0.666667       0.105263        0.004158              0.533333   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                     0.0                   0.0                       0.0   
1                     0.2                   0.0                       0.0   
2                     0.2                   0.0                       0.0   
3                     0.2                   0.0                       0.0   
4                     0.0                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                  0.0                   0.0                       0.0   
2122                  0.0                   0.0                       0.0   
2123                  0.0                   0.0                       0.0   
2124                  0.0                   0.0                       0.0   
2125                  0.0                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                            0.813333                              0.044118   
1                            0.066667                              0.279412   
2                            0.053333                              0.279412   
3                            0.053333                              0.323529   
4                            0.053333                              0.323529   
...                               ...                                   ...   
2121                         0.893333                              0.000000   
2122                         0.880000                              0.029412   
2123                         0.893333                              0.029412   
2124                         0.880000                              0.029412   
2125                         0.826667                              0.029412   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                              0.472527       ...   
1                                              0.000000       ...   
2                                              0.000000       ...   
3                                              0.000000       ...   
4                                              0.000000       ...   
...                                                 ...       ...   
2121                                           0.274725       ...   
2122                                           0.241758       ...   
2123                                           0.219780       ...   
2124                                           0.296703       ...   
2125                                           0.395604       ...   

      histogram_width  histogram_min  histogram_max  \
0            0.344633       0.110092       0.034483   
1            0.717514       0.165138       0.655172   
2            0.717514       0.165138       0.655172   
3            0.644068       0.027523       0.413793   
4            0.644068       0.027523       0.413793   
...               ...            ...            

In [7]:
class KNN_EUCLIDEAN:
    def __init__(self, k):
        self.K=k
        
    def train(self, x,y):
        self.X_train = x
        self.y_train = y
        
    def jarak(self, x1, x2):
        return np.sqrt(np.sum((x1-x2)**2))
    
    def _prediksi(self, x):
        #hitung jarak kesemua data dtraning
        jarak_titik = [self.jarak(x,X_train) for X_train in self.X_train]
        #urutkan berdasarkan jarak terdekat, ambil sejumlah K
        k_terbaik = np.argsort(jarak_titik)[:self.K]
        #ambil label k_terbaik
        label_k_terbaik = [self.y_train[i] for i in k_terbaik]
        #voting yang paling banyak
        hasil_voting = Counter(label_k_terbaik).most_common(1)
        return hasil_voting[0][0]
    
    def predict(self, X):
        y_prediksi = [self._prediksi(x) for x in X]
        return np.array(y_prediksi)

In [8]:
class KNN_MANHATTAN:
    def __init__(self, k):
        self.K=k
        
    def train(self, x,y):
        self.X_train = x
        self.y_train = y
        
    def jarak(self, x1, x2):
        return np.sum(abs(x1-x2))
    
    def _prediksi(self, x):
        #hitung jarak kesemua data dtraning
        jarak_titik = [self.jarak(x,X_train) for X_train in self.X_train]
        #urutkan berdasarkan jarak terdekat, ambil sejumlah K
        k_terbaik = np.argsort(jarak_titik)[:self.K]
        #ambil label k_terbaik
        label_k_terbaik = [self.y_train[i] for i in k_terbaik]
        #voting yang paling banyak
        hasil_voting = Counter(label_k_terbaik).most_common(1)
        return hasil_voting[0][0]
    
    def predict(self, X):
        y_prediksi = [self._prediksi(x) for x in X]
        return np.array(y_prediksi)

In [9]:
def jarak_minkowski(x1, x2, p): 
    equ_part1 = np.sum(np.power(np.abs(x1 - x2), p))
    distance = np.power(equ_part1, 1 / p)
    return np.round(distance, 3)

In [10]:
class KNN_MINKOWSKI:
    def __init__(self, k, p):
        self.K=k
        self.P=p
        
    def train(self, x,y):
        self.X_train = x
        self.y_train = y
    
    def _prediksi(self, x1):
        #hitung jarak kesemua data dtraning
        jarak_titik = [jarak_minkowski(x1, x2, self.P) for x2 in self.X_train]
        #urutkan berdasarkan jarak terdekat, ambil sejumlah K
        k_terbaik = np.argsort(jarak_titik)[:self.K]
        #ambil label k_terbaik
        label_k_terbaik = [self.y_train[i] for i in k_terbaik]
        #voting yang paling banyak
        hasil_voting = Counter(label_k_terbaik).most_common(1)
        return hasil_voting[0][0]
    
    def predict(self, X):
        y_prediksi = [self._prediksi(x) for x in X]
        return np.array(y_prediksi)

In [11]:
kf = KFold(n_splits=5, random_state=0, shuffle=True)
print(kf)

KFold(n_splits=5, random_state=0, shuffle=True)


In [12]:
import statsmodels.api as sm 
sl = 0.05
X = np.append(arr = np.ones((2126,0)).astype(int), values = dataset, axis = 1) 
X_opt = X[:]
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

def backwardElimination(X, sl):
    numVars = len(X[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, X).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    X = np.delete(X, j, 1)
                    regressor_OLS.summary()
    return X

SL = 0.05
X_train_opt = X[:]
X_Modeled = backwardElimination(X_train_opt, SL)

In [13]:
df = pd.DataFrame(X)
df

0         1         2         3    4    5    6         7   \
0     0.259259  0.000000  0.000000  0.000000  0.0  0.0  0.0  0.813333   
1     0.481481  0.315789  0.000000  0.400000  0.2  0.0  0.0  0.066667   
2     0.500000  0.157895  0.000000  0.533333  0.2  0.0  0.0  0.053333   
3     0.518519  0.157895  0.000000  0.533333  0.2  0.0  0.0  0.053333   
4     0.481481  0.368421  0.000000  0.533333  0.0  0.0  0.0  0.053333   
...        ...       ...       ...       ...  ...  ...  ...       ...   
2121  0.629630  0.000000  0.000000  0.466667  0.0  0.0  0.0  0.893333   
2122  0.629630  0.052632  0.000000  0.466667  0.0  0.0  0.0  0.880000   
2123  0.629630  0.052632  0.000000  0.466667  0.0  0.0  0.0  0.893333   
2124  0.629630  0.052632  0.000000  0.400000  0.0  0.0  0.0  0.880000   
2125  0.666667  0.105263  0.004158  0.533333  0.0  0.0  0.0  0.826667   

            8         9   ...        11        12        13        14   15  \
0     0.044118  0.472527  ...  0.344633  0.110092  0.034483  0.111111  0.0   
1     0.279412  0.000000  ...  0.717514  0.165138  0.655172  0.333333  0.1   
2     0.279412  0.000000  ...  0.717514  0.165138  0.655172  0.277778  0.1   
3     0.323529  0.000000  ...  0.644068  0.027523  0.413793  0.611111  0.0   
4     0.323529  0.000000  ...  0.644068  0.027523  0.413793  0.500000  0.0   
...        ...       ...  ...       ...       ...       ...       ...  ...   
2121  0.000000  0.274725  ...  0.209040  0.798165  0.474138  0.222222  0.0   
2122  0.029412  0.241758  ...  0.355932  0.486239  0.405172  0.333333  0.0   
2123  0.029412  0.219780  ...  0.361582  0.486239  0.413793  0.277778  0.0   
2124  0.029412  0.296703  ...  0.355932  0.486239  0.405172  0.333333  0.0   
2125  0.029412  0.395604  ...  0.220339  0.614679  0.318966  0.111111  0.1   

            16        17        18        19   20  
0     0.472441  0.587156  0.403670  0.271375  1.0  
1     0.637795  0.577982  0.577982  0.044610  0.5  
2     0.637795  0.568807  0.559633  0.048327  0.5  
3     0.606299  0.559633  0.550459  0.048327  1.0  
4     0.606299  0.577982  0.559633  0.040892  1.0  
...        ...       ...       ...       ...  ...  
2121  0.732283  0.706422  0.688073  0.007435  0.5  
2122  0.724409  0.688073  0.678899  0.011152  1.0  
2123  0.732283  0.688073  0.688073  0.014870  1.0  
2124  0.724409  0.678899  0.678899  0.014870  1.0  
2125  0.669291  0.642202  0.623853  0.003717  0.5  

[2126 rows x 21 columns]

In [14]:
df = pd.DataFrame(X_Modeled)
df

0         1    2    3         4         5         6         7   \
0     0.259259  0.000000  0.0  0.0  0.813333  0.472527  0.047337  0.344633   
1     0.481481  0.400000  0.0  0.0  0.066667  0.000000  0.205128  0.717514   
2     0.500000  0.533333  0.0  0.0  0.053333  0.000000  0.264300  0.717514   
3     0.518519  0.533333  0.0  0.0  0.053333  0.000000  0.453649  0.644068   
4     0.481481  0.533333  0.0  0.0  0.053333  0.000000  0.392505  0.644068   
...        ...       ...  ...  ...       ...       ...       ...       ...   
2121  0.629630  0.466667  0.0  0.0  0.893333  0.274725  0.142012  0.209040   
2122  0.629630  0.466667  0.0  0.0  0.880000  0.241758  0.140039  0.355932   
2123  0.629630  0.466667  0.0  0.0  0.893333  0.219780  0.120316  0.361582   
2124  0.629630  0.400000  0.0  0.0  0.880000  0.296703  0.138067  0.355932   
2125  0.666667  0.533333  0.0  0.0  0.826667  0.395604  0.098619  0.220339   

            8         9         10        11        12   13  
0     0.110092  0.034483  0.472441  0.403670  0.271375  1.0  
1     0.165138  0.655172  0.637795  0.577982  0.044610  0.5  
2     0.165138  0.655172  0.637795  0.559633  0.048327  0.5  
3     0.027523  0.413793  0.606299  0.550459  0.048327  1.0  
4     0.027523  0.413793  0.606299  0.559633  0.040892  1.0  
...        ...       ...       ...       ...       ...  ...  
2121  0.798165  0.474138  0.732283  0.688073  0.007435  0.5  
2122  0.486239  0.405172  0.724409  0.678899  0.011152  1.0  
2123  0.486239  0.413793  0.732283  0.688073  0.014870  1.0  
2124  0.486239  0.405172  0.724409  0.678899  0.014870  1.0  
2125  0.614679  0.318966  0.669291  0.623853  0.003717  0.5  

[2126 rows x 14 columns]

In [15]:
def accuracy(y_true,y_pred):
        accuracy= np.sum(y_true == y_pred)/len(y_true)
        return accuracy
print("MENGGUNAKAN EUCLIDEAN DISTANCE")

from collections import Counter
import statistics as st
hasil1 = []
for i in range (3, 10, 2):
    pred1 = []
    print('K =', i) 
    start1 = time.time()
    model = KNN_EUCLIDEAN(k=i)
    for train_index, test_index in kf.split(X_Modeled):
        X_train, X_test = X_Modeled[train_index], X_Modeled[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.train(X_train,y_train)
        y_pred = model.predict(X_test)
        end1 = time.time()
        acc = accuracy(y_test, y_pred)
        pred1.append(accuracy(y_test, y_pred))
        
        print(confusion_matrix(y_test, y_pred)) 
        print(classification_report(y_test, y_pred))
         
        
    print("akurasi : ", np.mean(pred1))
    hasil1.append(np.mean(pred1))
    print("akurasi 5-fold : ", pred1)

    #classification
    data1 = []
    for i in y_pred:
        data1.append(int(i))
        
    modus = st.mode(data1)
    print("Hasil Klasifikasi : ", modus)
print(hasil1)

print("\nMENGGUNAKAN MANHATTAN DISTANCE")
hasil2 = []
for i in range (3, 10, 2):
    pred2 = []
    print('K =', i) 
    start2 = time.time()
    model = KNN_MANHATTAN(k=i)
    for train_index, test_index in kf.split(X_Modeled):
        X_train, X_test = X_Modeled[train_index], X_Modeled[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.train(X_train,y_train)
        y_pred = model.predict(X_test)
        end2 = time.time()
        acc = accuracy(y_test, y_pred)
        pred2.append(accuracy(y_test, y_pred))
        
        print(confusion_matrix(y_test, y_pred)) 
        print(classification_report(y_test, y_pred))
         
    print("akurasi : ", np.mean(pred2))
    hasil2.append(np.mean(pred2))
    print("akurasi 5-fold : ", pred2)

    #classification
    data2 = []
    for i in y_pred:
        data2.append(int(i))
        
    modus = st.mode(data2)
    print("Hasil Klasifikasi : ", modus)
print(hasil2)

print("\nMENGGUNAKAN MINKOWSKI DISTANCE")
hasil3 = []
for i in range (3, 10, 2):
    pred3 = []
    print('K =', i) 
    p = 3
    start3 = time.time()
    model = KNN_MINKOWSKI(k=i, p=p)
    for train_index, test_index in kf.split(X_Modeled):
        X_train, X_test = X_Modeled[train_index], X_Modeled[test_index]
        y_train, y_test = y[train_index], y[test_index]
        model.train(X_train,y_train)
        y_pred = model.predict(X_test)
        end3 = time.time()
        acc = accuracy(y_test, y_pred)
        pred3.append(acc)
        
        print(confusion_matrix(y_test, y_pred)) 
        print(classification_report(y_test, y_pred))
         
    print("akurasi : ", np.mean(pred3))
    hasil3.append(np.mean(pred3))
    print("akurasi 5-fold : ", pred3)

    #classification
    data3 = []
    for i in y_pred:
        data3.append(int(i))
        
    modus = st.mode(data3)
    print("Hasil Klasifikasi : ", modus)
print(hasil3)
print(f"Runtime KNN with Euclidean Distance : {end1-start1}")
print(f"Runtime KNN with Manhattan Distance : {end2-start2}")
print(f"Runtime KNN with Minkowski Distance : {end3-start3}")

MENGGUNAKAN EUCLIDEAN DISTANCE
K = 3
[[313  11   2]
 [ 19  36   3]
 [  5   5  32]]
              precision    recall  f1-score   support

           1       0.93      0.96      0.94       326
           2       0.69      0.62      0.65        58
           3       0.86      0.76      0.81        42

    accuracy                           0.89       426
   macro avg       0.83      0.78      0.80       426
weighted avg       0.89      0.89      0.89       426

[[327   3   0]
 [ 23  41   4]
 [  1   3  23]]
              precision    recall  f1-score   support

           1       0.93      0.99      0.96       330
           2       0.87      0.60      0.71        68
           3       0.85      0.85      0.85        27

    accuracy                           0.92       425
   macro avg       0.89      0.82      0.84       425
weighted avg       0.92      0.92      0.91       425

[[325   8   0]
 [ 18  34   4]
 [  5   4  27]]
              precision    recall  f1-score   support

        

[[325  10   0]
 [ 20  34   2]
 [ 11   3  20]]
              precision    recall  f1-score   support

           1       0.91      0.97      0.94       335
           2       0.72      0.61      0.66        56
           3       0.91      0.59      0.71        34

    accuracy                           0.89       425
   macro avg       0.85      0.72      0.77       425
weighted avg       0.89      0.89      0.89       425

[[326   4   1]
 [ 20  35   2]
 [  3  10  24]]
              precision    recall  f1-score   support

           1       0.93      0.98      0.96       331
           2       0.71      0.61      0.66        57
           3       0.89      0.65      0.75        37

    accuracy                           0.91       425
   macro avg       0.85      0.75      0.79       425
weighted avg       0.90      0.91      0.90       425

akurasi :  0.8951162662247997
akurasi 5-fold :  [0.8779342723004695, 0.92, 0.88, 0.8917647058823529, 0.9058823529411765]
Hasil Klasifikasi :  1
[0

[[329   1   0]
 [ 26  41   1]
 [  3   4  20]]
              precision    recall  f1-score   support

           1       0.92      1.00      0.96       330
           2       0.89      0.60      0.72        68
           3       0.95      0.74      0.83        27

    accuracy                           0.92       425
   macro avg       0.92      0.78      0.84       425
weighted avg       0.92      0.92      0.91       425

[[328   4   1]
 [ 21  29   6]
 [  6   7  23]]
              precision    recall  f1-score   support

           1       0.92      0.98      0.95       333
           2       0.72      0.52      0.60        56
           3       0.77      0.64      0.70        36

    accuracy                           0.89       425
   macro avg       0.81      0.71      0.75       425
weighted avg       0.88      0.89      0.89       425

[[324  11   0]
 [ 21  33   2]
 [  9   3  22]]
              precision    recall  f1-score   support

           1       0.92      0.97      0.94  

[[325   6   0]
 [ 20  36   1]
 [  3   8  26]]
              precision    recall  f1-score   support

           1       0.93      0.98      0.96       331
           2       0.72      0.63      0.67        57
           3       0.96      0.70      0.81        37

    accuracy                           0.91       425
   macro avg       0.87      0.77      0.81       425
weighted avg       0.91      0.91      0.91       425

akurasi :  0.8965324495995581
akurasi 5-fold :  [0.8685446009389671, 0.9223529411764706, 0.8847058823529412, 0.8964705882352941, 0.9105882352941177]
Hasil Klasifikasi :  1
K = 9
[[317   8   1]
 [ 27  30   1]
 [  7   6  29]]
              precision    recall  f1-score   support

           1       0.90      0.97      0.94       326
           2       0.68      0.52      0.59        58
           3       0.94      0.69      0.79        42

    accuracy                           0.88       426
   macro avg       0.84      0.73      0.77       426
weighted avg       0.88

In [16]:
df = pd.DataFrame(X_test)
df

0         1    2    3         4         5         6         7   \
0    0.814815  0.066667  0.0  0.0  0.693333  0.087912  0.581854  0.717514   
1    0.407407  0.200000  0.0  0.0  0.986667  0.868132  0.057199  0.073446   
2    0.333333  0.000000  0.0  0.0  0.986667  0.791209  0.078895  0.050847   
3    0.481481  0.066667  0.0  0.0  0.226667  0.000000  0.297830  0.796610   
4    0.259259  0.066667  0.0  0.0  0.213333  0.000000  0.428008  0.694915   
..        ...       ...  ...  ...       ...       ...       ...       ...   
420  0.500000  0.533333  0.0  0.0  0.773333  0.065934  0.049310  0.367232   
421  0.555556  0.600000  0.0  0.0  0.880000  0.296703  0.090730  0.225989   
422  0.555556  0.400000  0.0  0.4  0.680000  0.000000  0.098619  0.463277   
423  0.629630  0.533333  0.0  0.0  0.893333  0.219780  0.167653  0.129944   
424  0.629630  0.466667  0.0  0.0  0.893333  0.219780  0.120316  0.361582   

           8         9         10        11        12   13  
0    0.055046  0.551724  0.708661  0.678899  0.037175  1.0  
1    0.587156  0.068966  0.535433  0.477064  0.000000  1.0  
2    0.623853  0.068966  0.503937  0.440367  0.000000  0.5  
3    0.000000  0.620690  0.574803  0.486239  0.130112  0.5  
4    0.045872  0.508621  0.480315  0.449541  0.092937  0.5  
..        ...       ...       ...       ...       ...  ...  
420  0.376147  0.318966  0.574803  0.532110  0.011152  0.5  
421  0.568807  0.284483  0.614173  0.568807  0.000000  0.5  
422  0.155963  0.258621  0.582677  0.467890  0.197026  1.0  
423  0.678899  0.241379  0.661417  0.623853  0.003717  1.0  
424  0.486239  0.413793  0.732283  0.688073  0.014870  1.0  

[425 rows x 14 columns]

In [17]:
import statsmodels.api as sm 
sl = 0.05
regressor_OLS = sm.OLS(endog = y, exog = X_Modeled).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.607
Model:                            OLS   Adj. R-squared:                  0.604
Method:                 Least Squares   F-statistic:                     250.5
Date:                Mon, 28 Nov 2022   Prob (F-statistic):               0.00
Time:                        15:26:48   Log-Likelihood:                -988.87
No. Observations:                2126   AIC:                             2006.
Df Residuals:                    2112   BIC:                             2085.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8148      0.093      8.787      0.000       0.633       0.997
x2            -0.3375      0.047     -7.163      0.000      -0.430      -0.245
x3             0.7657      0.155      4.946      0.000       0.462       1.069
x4             1.8521      0.101     18.250      0.000       1.653       2.051
x5             0.6552      0.046     14.332      0.000       0.566       0.745
x6             1.0629      0.053     19.974      0.000       0.959       1.167
x7             0.2937      0.086      3.413      0.001       0.125       0.462
x8             2.9797      0.171     17.470      0.000       2.645       3.314
x9             2.1773      0.108     20.212      0.000       1.966       2.389
x10           -1.5326      0.159     -9.639      0.000      -1.844      -1.221
x11           -0.5165      0.191     -2.700      0.007      -0.892      -0.141
x12           -1.4921      0.244     -6.123      0.000      -1.970      -1.014
x13            0.7561      0.118      6.396      0.000       0.524       0.988
x14            0.1650      0.046      3.559      0.000       0.074       0.256
==============================================================================
Omnibus:                      244.156   Durbin-Watson:                   0.891
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              527.245
Skew:                           0.695   Prob(JB):                    3.24e-115
Kurtosis:                       5.005   Cond. No.                         53.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:

# cm = confusion_matrix(y_test, y_pred)
# print(cm)

In [19]:
import statsmodels.api as sm 
sl = 0.05
regressor_OLS = sm.OLS(endog = y, exog = dataset).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.607
Model:                            OLS   Adj. R-squared:                  0.604
Method:                 Least Squares   F-statistic:                     162.8
Date:                Mon, 28 Nov 2022   Prob (F-statistic):               0.00
Time:                        15:26:48   Log-Likelihood:                -986.93
No. Observations:                2126   AIC:                             2016.
Df Residuals:                    2105   BIC:                             2135.
Df Model:                          20                                         
Covariance Type:            nonrobust                                         
==========================================================================================================================
                                                             coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------------
baseline_value                                             0.8344      0.119      6.995      0.000       0.600       1.068
accelerations                                              0.0026      0.070      0.037      0.970      -0.135       0.140
fetal_movement                                             0.0405      0.092      0.439      0.661      -0.140       0.221
uterine_contractions                                      -0.3434      0.048     -7.096      0.000      -0.438      -0.248
light_decelerations                                       -0.0517      0.079     -0.654      0.513      -0.207       0.103
severe_decelerations                                       0.7611      0.156      4.879      0.000       0.455       1.067
prolongued_decelerations                                   1.8110      0.118     15.397      0.000       1.580       2.042
abnormal_short_term_variability                            0.6455      0.051     12.716      0.000       0.546       0.745
mean_value_of_short_term_variability                       0.0113      0.112      0.102      0.919      -0.207       0.230
percentage_of_time_with_abnormal_long_term_variability     1.0663      0.057     18.742      0.000       0.955       1.178
mean_value_of_long_term_variability                        0.2944      0.109      2.697      0.007       0.080       0.509
histogram_width                                            3.0747      0.227     13.554      0.000       2.630       3.520
histogram_min                                              2.2395      0.134     16.658      0.000       1.976       2.503
histogram_max                                             -1.5781      0.180     -8.784      0.000      -1.930      -1.226
histogram_number_of_peaks                                 -0.0527      0.079     -0.669      0.504      -0.207       0.102
histogram_number_of_zeroes                                 0.1239      0.129      0.958      0.338      -0.130       0.378
histogram_mode                                            -0.4697      0.195     -2.405      0.016      -0.853      -0.087
histogram_mean                                            -0.3831      0.263     -1.456      0.146      -0.899       0.133
histogram_median                                          -1.2205      0.328     -3.724      0.000      -1.863      -0.578
histogram_variance                                         0.7513      0.125      5.988      0.000       0.505       0.997
histogram_tendency                                         0.1650      0.047      3.537      0.000       0.074       0.256
==============================================================================
Omnibus:                      237.892   Durbin-Watso

In [ ]:
# def diss(j):
#     dis_i = []
#     for i in range (len(X)):
#         #print("i ",i)
#         dis_i.append(KNN_EUCLIDEAN.jarak_euclidean(X[i],X[j]))
# #     print("=========================")
#     return dis_i
# # print(diss(2))
# dis = []
# for i in range (len(X)):
#     dis.append(diss(i))

# for i in range (len(dis)):
#     arr1 = np.sort(dis[i])
#     print(arr1[1:6])